///////////////////////////////////////////////////////////////////////////////
// TcAsyncBufferWritingModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcAsyncBufferWritingModule.h"
#include "TcTimeConversion.h"    //getsystime

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CTcAsyncBufferWritingModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CTcAsyncBufferWritingModule
BEGIN_INTERFACE_MAP(CTcAsyncBufferWritingModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CTcAsyncBufferWritingModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CTcAsyncBufferWritingModule)
IMPLEMENT_ITCADI(CTcAsyncBufferWritingModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CTcAsyncBufferWritingModule 
BEGIN_SETOBJPARA_MAP(CTcAsyncBufferWritingModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcAsyncBufferWritingModuleParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CTcAsyncBufferWritingModule 
BEGIN_GETOBJPARA_MAP(CTcAsyncBufferWritingModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcAsyncBufferWritingModuleParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CTcAsyncBufferWritingModule
BEGIN_OBJDATAAREA_MAP(CTcAsyncBufferWritingModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_TcAsyncBufferWritingModuleInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_TcAsyncBufferWritingModuleOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CTcAsyncBufferWritingModule::CTcAsyncBufferWritingModule()
	: m_counter(0)
{
	memset(&m_Parameter, 0, sizeof(m_Parameter)); 
	memset(&m_Inputs, 0, sizeof(m_Inputs)); 
	memset(&m_Outputs, 0, sizeof(m_Outputs)); 

	memset(&m_Buffer1, 0, sizeof(m_Buffer1));
	memset(&m_Buffer2, 0, sizeof(m_Buffer2));

	m_pBufferFill = m_Buffer1;
	m_nBufferFillIndex = 0;
	m_pBufferWrite = NULL;
	titleflag = TRUE;
}

///////////////////////////////////////////////////////////////////////////////
CTcAsyncBufferWritingModule::~CTcAsyncBufferWritingModule() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CTcAsyncBufferWritingModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CTcAsyncBufferWritingModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;

	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccessAsync, m_spFileAccessAsync.GetIID(), (PPVOID)(&m_spFileAccessAsync)); 

	if (SUCCEEDED(hr))
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccessAsync;

		OTCID oid = m_spCyclicCaller.GetOID();
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncAdsProvider, sizeof(oid), &oid); 
		if (m_Parameter.SegmentSize == 0)
		{
			hr = ADS_E_INVALIDPARM; 
		}
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncSegmentSize, sizeof(m_Parameter.SegmentSize), &m_Parameter.SegmentSize); 
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjPara(PID_TcFileAccessAsyncTimeoutMs, sizeof(m_Parameter.Timeout), &m_Parameter.Timeout); 
		hr = FAILED(hr) ? hr : spFileAccessObj->TcSetObjState(TCOM_STATE_SAFEOP, m_spSrv, NULL); 
	}

	TRACE(FTEXT("hr=0x%08x"), hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CTcAsyncBufferWritingModule::SetObjStateSO()
{
	HRESULT hr = S_OK;

	hr = AddModuleToCaller(); 

	// TODO: Add any additional initialization
	if (SUCCEEDED(hr))
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccessAsync;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_OP, m_spSrv, NULL); 
	}

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CTcAsyncBufferWritingModule::SetObjStateOS()
{
	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CTcAsyncBufferWritingModule::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}

#define TIMESTAMPSTR "%04d-%02d-%02d-%02d-%02d-%02d-%03d"
#define TIMESTAMPPARM(st) st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond, st.wMilliseconds

///////////////////////////////////////////////////////////
// ITcCyclic
///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CTcAsyncBufferWritingModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;
	//m_Outputs.setaussenT = (double)17.0;
	//m_Outputs.setroomT = (double)20.0;
	m_Outputs.setwasserT = (double)90.0;

	//make title file
	if (titleflag) {
		hr = m_fsmFileTitleWriter.Init
		(
			m_spSrv,
			m_spFileAccessAsync,
			"%TC_BOOTPRJPATH%TTITLETEST.txt",
			reinterpret_cast<PVOID>(Title),
			A.length() * sizeof(char)
		);
	}
	if (SUCCEEDED(hr))
	{
		titleflag = NULL;
	}

		
	if (m_fsmFileTitleWriter.IsActive())
	{
		hr = m_fsmFileTitleWriter.Eval();
	}
	
	
	// UTC at "begin of task" in 100 ns intervals since 1.1.1601
	hr = FAILED(hr) ? hr : ipTask->GetCurrentSysTime(&systime);
	SYSTEMTIME stSysTime;
	TcFileTimeToSystemTime(systime, &stSysTime);
	sprintf(m_szTaskSysTime, TIMESTAMPSTR, TIMESTAMPPARM(stSysTime));

	if (FillBuffer(m_pBufferFill, ASYNCWRITE_BUFFERSIZE, m_nBufferFillIndex))
	{
		if (m_nBufferFillIndex == 0)
		{
			m_counter++;
			sprintf(bu, "%s%s", m_szTaskSysTime, "ATEST.txt");
			sprintf(buf, "%s%s", "%TC_BOOTPRJPATH%", bu);
			name = buf;
			// this indicates that the buffer is full, switch to other buffer
			if (m_pBufferFill == m_Buffer1)
			{
				m_pBufferFill = m_Buffer2;
				m_pBufferWrite = m_Buffer1; 
			}
			else
			{
				m_pBufferFill = m_Buffer1;
				m_pBufferWrite = m_Buffer2;
			}
		}
	}

	if (!m_Inputs.DisableWrite)
	{
		if (m_pBufferWrite)
		{
			hr = 
				m_fsmFileWriter.Init
				(
					m_spSrv,
					m_spFileAccessAsync,
					name,
					reinterpret_cast<PVOID>(m_pBufferWrite), 
					ASYNCWRITE_BUFFERSIZE*sizeof(st_Buffer)
				); 
		}
		if (SUCCEEDED(hr))
		{
			m_pBufferWrite = NULL;
		}
	}

	if (m_fsmFileWriter.IsActive())
	{
		m_Outputs.WriteActive = TRUE;
		hr = m_fsmFileWriter.Eval();
		if (SUCCEEDED(hr))
		{
			m_Outputs.BytesWritten = m_fsmFileWriter.GetBytesWrittenTotal();
		}
	}
	else
	{
		m_Outputs.WriteActive = FALSE;
	}
	return hr;
}
///</AutoGeneratedContent>

BOOL CTcAsyncBufferWritingModule::FillBuffer
(
	st_Buffer* pBuffer,
	//float* pBuffer, 
	UINT nBuffer, 
	UINT& nBufferIndex
)
{

	if (nBufferIndex<nBuffer)
	{
		m_counters++;
		//strcpy(pBuffer[nBufferIndex].Timestamp, m_szTaskSysTime);
		//sprintf(roomT, "%lf", m_counters);
		//strcpy(pBuffer[nBufferIndex].roomtemp, roomT);
		//sprintf(waterT, "%lf", m_counters);
		//strcpy(pBuffer[nBufferIndex].signal3, waterT);
		/*sprintf(s3, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal4, s3);
		sprintf(s4, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal5, s4);
		sprintf(s5, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal6, s5);
		sprintf(s6, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal7, s6);
		sprintf(s7, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal4, s7);
		sprintf(s8, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal5, s8);
		sprintf(s9, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal6, s9);
		sprintf(s10, "%lf", m_counters);
		strcpy(pBuffer[nBufferIndex].signal7, s10);*/
		pBuffer[nBufferIndex].Timestamp = systime;
		pBuffer[nBufferIndex].roomtemp = m_counters;
		pBuffer[nBufferIndex].watertemp = m_counters + 1;
		pBuffer[nBufferIndex].signal3 = m_counters;
		pBuffer[nBufferIndex].signal4 = m_counters;
		pBuffer[nBufferIndex].signal5 = m_counters;
		pBuffer[nBufferIndex].signal6 = m_counters;
		pBuffer[nBufferIndex].signal7 = m_counters;
		pBuffer[nBufferIndex].signal8 = m_counters;
		pBuffer[nBufferIndex].signal9 = m_counters;
		pBuffer[nBufferIndex].signal10 = m_counters;
		/*pBuffer[nBufferIndex].roomtemp = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].watertemp = static_cast<double>(m_counters+1);
		pBuffer[nBufferIndex].signal3 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal4 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal5 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal6 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal7 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal8 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal9 = static_cast<double>(m_counters);
		pBuffer[nBufferIndex].signal10 = static_cast<double>(m_counters);*/
		++nBufferIndex;
		if (nBufferIndex == nBuffer)
		{
			nBufferIndex = 0;
		}
		return TRUE;
	}
	else
	{
		return FALSE;
	}
}


///////////////////////////////////////////////////////////////////////////////
HRESULT CTcAsyncBufferWritingModule::AddModuleToCaller()
{
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CTcAsyncBufferWritingModule::RemoveModuleFromCaller()
{
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
}



