<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{ea0b4a2c-0bed-406f-a5c3-9ef6d33ee418}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	XMLTesten : XMLTesten;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[XMLTesten();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>